name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        continue-on-error: false

      - name: Run unit tests
        run: npm test
        continue-on-error: false

      - name: Run integration tests
        run: npm run test:integration
        continue-on-error: false

      - name: Build project
        run: npm run build
        continue-on-error: false

      - name: Test coverage
        run: npm run test:coverage
        continue-on-error: true  # Don't fail if coverage command doesn't exist

  validate-action:
    name: Validate Action
    runs-on: ubuntu-latest
    needs: test  # Only run after tests pass
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test action syntax
        run: |
          # Validate action.yml syntax
          if [ -f "action.yml" ]; then
            echo "✅ action.yml found"
            # Basic YAML validation
            python -c "import yaml; yaml.safe_load(open('action.yml'))" || exit 1
            echo "✅ action.yml is valid YAML"
          fi

      - name: Check required files
        run: |
          echo "Checking required files..."
          
          # Check for essential files
          test -f "package.json" && echo "✅ package.json exists"
          test -f "README.md" && echo "✅ README.md exists"
          
          # Check for test files
          if [ -d "__tests__" ] || [ -d "test" ] || [ -d "tests" ]; then
            echo "✅ Test directory found"
          else
            echo "❌ No test directory found"
            exit 1
          fi

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true  # Don't fail on low-severity issues

      - name: Check for secrets
        run: |
          echo "Checking for potential secrets in code..."
          # Basic check for common secret patterns
          if grep -r "sk_" --include="*.js" --include="*.ts" --include="*.json" . || \
             grep -r "pk_" --include="*.js" --include="*.ts" --include="*.json" . || \
             grep -r "api_key" --include="*.js" --include="*.ts" --include="*.json" . || \
             grep -r "secret" --include="*.js" --include="*.ts" --include="*.json" .; then
            echo "⚠️  Potential secrets found in code. Please review."
            exit 1
          else
            echo "✅ No obvious secrets detected"
          fi

  # This job will only run if all other jobs pass
  all-checks:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [test, validate-action, security]
    
    steps:
      - name: Success
        run: |
          echo "🎉 All checks passed! PR is ready for review."
          echo "✅ Tests completed successfully"
          echo "✅ Action validation passed"
          echo "✅ Security checks passed"
